server:
  port: 8766
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ningquenan/config-repo
          username: 13698250206
          password: 123456abc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#±©Â¶bus-refresh  *È«±©Â¶
management:
  endpoints:
    web:
      exposure:
        include: "*"
