server:
  port: 8762
spring:
  application:
    name: eureka2

eureka:
  server:
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
